ersion: 0.0
Resources:
  - MaintenanceScreenApp:
      Type: AWS::CloudFormation::Stack
      Properties:
        StackName: maintenance-screen-app
        TemplateURL: https://maintenance-buket.s3.amazonaws.com/cf-template.json

Hooks:
  ApplicationStart:
    - Location: scripts/maintenance-enable.sh
      Timeout: 300
      RunAs: root

  ApplicationStop:
    - Location: scripts/maintenance-disable.sh
      Timeout: 300
      RunAs: root

  ValidateService:
    - Location: scripts/validate-deployment.sh
      Timeout: 300
      RunAs: root

Files:
  - source: /
    destination: /var/www/maintenance-screen

Permissions:
  - object: /var/www/maintenance-screen
    pattern: "**"
    owner: ec2-user
    group: ec2-user