version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/maintenance-screen

permissions:
  - object: /var/www/maintenance-screen
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStop:
    - location: scripts/maintenance-enable.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/validate-deployment.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/maintenance-disable.sh
      timeout: 300
      runas: root